#!/bin/sh
set -e

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

error () {
  echo "$(basename "$0"): $*" >&2
  exit 1
}

start_context () {
  [ -n "$1" ] || return 1

  local shell_type="$1"
  local initrc="$SCRIPT_DIR/shell/$shell_type.initrc"

  case "$shell_type" in
    bash) exec "$SHELL" --init-file "$initrc" ;;
    zsh)
      # Move initrc to a temporary ZDOTDIR for zsh to source it
      export ZDOTDIR="$(mktemp -d)"
      cp "$initrc" "$ZDOTDIR/.zshrc"
      exec "$SHELL"
      ;;
    *) error "'$shell_type' shell is not supported yet" ;;
  esac
}

: "${CONTX_ENVRC:=.contxenv:.contx/envrc}"
export CONTX_ENVRC

# Source env file before session start to allow setting sensible envs
IFS=:
for file in $CONTX_ENVRC; do
  [ ! -f "$file" ] || . "$file"
done

: "${CONTX_INITRC:=.contxrc:.contx/initrc:.envrc:.env}"
: "${CONTX_FILES:=$CONTX_ENVRC:$CONTX_INITRC}"
export CONTX_INITRC
export CONTX_FILES

for file in $CONTX_FILES; do
  [ ! -f "$file" ] || local_files="${local_files+:}$(realpath $file)"
done
[ -n "$local_files" ] || error 'no context found in the current directory'
unset IFS

shell_type="$(basename "$(realpath "$SHELL")")"
start_context "$shell_type"
